### ISSUE TITLE
Distributed Ledger Design

### ISSUE THREAD

**Issue by torimcc** [LinuxForHealth/connect#124]
- "Shared"/decentralized ledger topic with pointer to TOPIC:PARTITION:OFFSET where record is stored in Kafka or the address pointer for IPFS. Or do we not use a topic and use a search index?
- Integration of IPFS for "off ledger" storage

**Comment by cdanup1** [comment]
[Initial ledger design PPT](https://app.zenhub.com/files/337464130/6e3c9631-dc87-4dd5-93e0-de2df7cdd708/download)
