### ISSUE TITLE
TLS All The Remaining Things

### ISSUE THREAD

**Issue by torimcc** [LinuxForHealth/connect#131]
[ ] - Validate how we use TLS 
[ ] - Contexts in pyConnect. Passing another server's private key in seems sketchy
[ ] - Kafka
   https://juplo.de/encrypt-communication-between-kafka-and-zookeeper-with-tls/
  https://www.confluent.io/blog/apache-kafka-security-authorization-authentication-encryption/
[ ] - Zookeeper

**Comment by ccorley** [comment]
Let's discuss `Passing another server's private key in seems sketchy`.  To my knowledge we are not doing this anywhere.
